[package]
name = "vanilla_validator_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "vanilla_validator_nif"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.2"

[dependencies.rustler_sys]
version = "2.0"

